"""added description to recipes

Revision ID: 5a9a68c17e24
Revises: b027f6d581d5
Create Date: 2026-05-20 20:16:06.787392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9a68c17e24'
down_revision: Union[str, Sequence[str], None] = 'b027f6d581d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('second_dishes')
    op.drop_table('sweets')
    op.drop_table('dishes')
    op.drop_table('drinks')
    op.drop_table('first_dishes')
    op.add_column('schedules', sa.Column('time_notification', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'time_notification')
    op.create_table('first_dishes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_cooking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('first_dishes_pkey'))
    )
    op.create_table('drinks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_cooking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('drinks_pkey'))
    )
    op.create_table('dishes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_dishes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('second_dishes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sweets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('drinks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drinks'], ['drinks.id'], name=op.f('dishes_drinks_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_dishes'], ['first_dishes.id'], name=op.f('dishes_first_dishes_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['second_dishes'], ['second_dishes.id'], name=op.f('dishes_second_dishes_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sweets'], ['sweets.id'], name=op.f('dishes_sweets_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('dishes_pkey'))
    )
    op.create_table('sweets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_cooking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sweets_pkey'))
    )
    op.create_table('second_dishes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_cooking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('second_dishes_pkey'))
    )
    # ### end Alembic commands ###
