"""add_users_table

Revision ID: fb525fb34a84
Revises: 5a9a68c17e24
Create Date: 2026-05-25 16:31:17.760244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb525fb34a84'
down_revision: Union[str, Sequence[str], None] = '5a9a68c17e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Створення таблиці користувачів
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    # ТУТ МИ ВИДАЛИЛИ DROP_TABLE, щоб база не сварилася!

    # Оновлення таблиці розкладу
    op.alter_column('schedules', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_schedules_scheduled_at'), 'schedules', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_scheduled_at'), table_name='schedules')
    op.alter_column('schedules', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_table('second_dishes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_cooking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('second_dishes_pkey'))
    )
    op.create_table('sweets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_cooking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sweets_pkey'))
    )
    op.create_table('first_dishes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_cooking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('first_dishes_pkey'))
    )
    op.create_table('dishes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_dishes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('second_dishes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sweets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('drinks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drinks'], ['drinks.id'], name=op.f('dishes_drinks_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_dishes'], ['first_dishes.id'], name=op.f('dishes_first_dishes_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['second_dishes'], ['second_dishes.id'], name=op.f('dishes_second_dishes_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sweets'], ['sweets.id'], name=op.f('dishes_sweets_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('dishes_pkey'))
    )
    op.create_table('drinks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_cooking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('drinks_pkey'))
    )
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
